script: bash ./deploy.sh
language: php
php:
- 5.5
env:
  global:
  - GH_REF: github.com/UDOOboard/Blu-Docs.git
  - secure: OAPAPZei7X6Eys3RuMhuWLSbThpLcUD58c/DWMl6jGoPokH8MZkpW+0Z2wPi92R+pitse3YklNf7fivalISGPA3tyw6Y7lR4G6TJLAtiN1HdnxEHA54F/npA4XxDgyWjWGcxPQi5XPFr9JRNFkhGDo76dH+2R3fMXATH7HzG5NtBJOvfA2z+1q1zEMCCR0sD1VgYLc6HO2VcxaCpM1Ii3ZC9v00OyNfwO3LQBVs2q5bCLnIky0JW6zsyjfW/D/f8fs7pTbxBsO4OZ2/+E3kC8ZHeTt4jUaxay4Pm8HPx38fdPfq/pETCCgmqc5Crhwb4RZDrZlMwc1z45KVQ3hNvQOluWNdoIFzXqZiK2CCNqisuqv7kMOIDWBYf/5aGrkHNTgR7SI+VSgF0dzxhHDIp1Lc6n6Dlwh+XrzWjzALcEDvpkW2yrjyrxINGiH1w8m3Z3J9Cq1bSFbu2ujLcbiA1h7PWO4OTGDWjIX4x9jo5DcxMEAYpZ72HJ2hRsMOHqtXjAll9DFUxV+jhWKO7QpEM3Z0zGfyUvN1TmoHkwHBNmVSc54FIdoOxgKo9pMx0mXLE56b3xG+Abcx9YKF+qJx5GmX0iVgoGhl5J/+GOTAjzHw6E4nyvDPs0A2mUSthwVOX3sJElqkuRPKuvU4e6WKSMfNMx8OCXiCl3cn0vULiKPk=
