script: bash ./deploy.sh
language: php
php:
- 5.5
env:
  global:
    - GH_REF: github.com/UDOOboard/Blu-Docs.git
    - secure: rsRYRLvJ2w4m54+8g8sy5EtAJeyXBoo4LY13CTTY5zlMroOwEtWlHfcynN2hukkDVwbCupSlu0Sm5H8wS4Jco2bGFBTUgGW4ubR/0F737LjLxIB50U6ov2O1gk8Zz0k5/xZVRru150aJKgmchXaBV7Y0EYUMirBfY21fbycxXQex3I2NVJyQJzP7gDFMASUaJ6+rUXA1usEXSpebNEN/1ovuvxDMBaqLy+lTD/fkR5KygSAggjLuNIxn5uy9cWjpIQfaPwSlegeyiITdRbVGeKgPo3q1qTI1cvzeF9iAbbM1fWxWbH4QhsyUipHM4KtBsGuMVGm67qcnVipBDZpdRgB74+i36ohsiBL/ncGRk4pITIkJ/jpD9Awt14+GRjGx3W68/Ga6Z2SpOlJXqpfPpysFRvc24C6gZyq6vM9hbXZWk+Xg5/j7LyKOmVyRECIOMFk5jx1edIsO68qNBvjNj6U3AlSit5Qb/JHC+16TmkJVhdx9z9zAcm6i9/97MDpcOqhDAP/ITIMpmUC7r7xJmsrdDwfaLnVoMxdwxKEWgFLu83rOblKCXypxCj+CtzTiQ1aF2J7jgw7w6fE+oV9PHG6erubCQ7sF1zX181BZhvt7HhyB0gkMtCMaZflw6JIChiWBwe4qXdBS+bO89NirBVjLHZTSNU7/5UHqvQurbZY=
